### ISSUE TITLE
Exercise 3

### ISSUE THREAD

**Issue by nimonian** [corndeladmin/swe-js-upgrade#4]
In the [js-doc example](https://github.com/corndeladmin/swe-js-upgrade/blob/ec090867d74817339cef13d12ddb525c0500a739/exercises/exercise-3.js#L14-L15) the function name bring called is different from the actual function name

**Comment by nimonian** [comment]
Also should the exercise file contain the typedefs?

**Comment by AndrewYHuang** [comment]
Added typedefs and fixed the function name issue!
