### ISSUE TITLE
Extension exercise

### ISSUE THREAD

**Issue by nimonian** [corndeladmin/swe-js-upgrade#6]
```js
/**
* isUpgradeAvailable(player, biggerStorage) // returns false
* isUpgradeAvailable(player, evenBiggerStorage) // returns true
* isUpgradeAvailable(player, mineralCompression) // returns false
* /
```

It would be really useful if these had explanations to say why the return value is what it is. E.g.

```js
// returns false, because it is already owned
```

**Comment by nimonian** [comment]
Also, when I run the tests with what I think is the right solution, I fail all tests with

```console
ReferenceError: biggerStorage is not defined
```

I think this might be an error in the tests rather than the solution?

**Comment by AndrewYHuang** [comment]
Should be fixed now - I missed adding in the actual upgrade objects
